#!/usr/bin/bash
if [ -z "$PYFILE" ]; then
    echo "PYFILE is not set" >&2
    exit 1
fi
echo "Compiling $PYFILE ..."
python3 -c "import py_compile; py_compile.compile('$PYFILE', cfile='$PYFILE' + 'c')"
